name: test

on:
  push:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"

  pull_request:
    branches:
      - main
      - "[0-9]+.[0-9]+.x"

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - uses: pre-commit/action@v3.0.0

      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()

      - name: Poetry Install
        run: |
          poetry install

      - name: Clean tests of any temp files
        run: |
          git clean -fd ./tests

      - name: Test without coverage
        run: poetry run python -m pytest .

      - name: Clean tests of any temp files
        run: |
          git clean -fd ./tests

      - name: Test with coverage
        run: poetry run python -m coverage run -m pytest .

      - name: Generate coverage report
        run: poetry run python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
